src/infer.ts
I have no understanding of deno, but I have the input.ts file from the older ndc-deno project with one func addition. There are no imports when `deno vendor` is run so the container fails to start because it errors when trying to read `./vendor/input_map/json`. This solves my problem, but not sure if it has other unintended consequences.
=> Check if vendor folder exists

Dockerfile, README.md, entrypoint.sh, src/connector.rs, src/infer.ts, src/server.ts
Ensure that only exported functions are listed in the schema.
Move more work into the docker build steps.
The user-facing change here is that you can no longer specify which function is your entrypoint.
You can still provide a directory of ts files, but only `index.ts` will act as the interface definition.
=> Hibernation and function export improvements

README.md, src/connector.ts
Adding documentation to readme for config format.
Closes: https://github.com/hasura/ndc-typescript-deno/issues/41
=> Documenting config format

CHANGELOG.md, README.md, src/connector.ts, src/infer.ts, src/mod.ts, src/test/conflicting_names_test.ts, src/test/data/conflicting_names.ts, src/test/data/conflicting_names_dep.ts, src/test/data/recursive.ts, src/test/data/type_parameters.ts, src/test/infer_test.ts, src/test/recursive_types_test.ts, src/test/type_parameters_test.ts, src/test/void_test.ts
Fixes: https://github.com/hasura/ndc-typescript-deno/issues/34
Fixes: https://github.com/hasura/ndc-typescript-deno/issues/30
This PR updates the TS Deno connector with the following changes:
* Depends on the latest version of the TS SDK which no longer needs multiregion functions
* Update path dep: https://deno.land/std@0.203.0/path/mod.ts
* Defines `arraybuffer` and `blob` scalars
* Sets `MAX_INFERENCE_RECURSION = 20` to break any potential infinite recursion loops
* Types names are now preserved when possible
* Types referenced from dependencies will be qualified by their path
* Tests have been created in the `test/` directory for the refactored inference cases
* conflicting_names_test.ts
* recursive_types_test.ts
* type_parameters_test.ts - ignored …
=> Updating SDK and Improving Inference

CHANGELOG.md, src/mod.ts
The value is never used anyway, so this was a bug that didn't even serve any purpose.
```diff
---const node_style_args = [Deno.execPath(), path.fromFileUrl(import.meta.url), ...Deno.args];
+++const node_style_args = [Deno.execPath(), import.meta.url, ...Deno.args];
```
Doesn't trigger when running against a local copy of the connector, but does occur when invoking from deno.land.
Causes the following:
```
> deno run -A --watch --check https://deno.land/x/hasura_typescript_connector@v0.10/mod.ts serve --configuratio
n ./config.json
Watcher Process started.
error: Uncaught TypeError: Must be a file URL.
throw new TypeError("Must be a file URL.");
```
This wasn't caught in testing since it needs to be published before it can be invoked in a way that fails.
=> Fixing silly bug in entrypoint due to parsing hosted URL as a file

CHANGELOG.md, src/infer.ts, src/test/data/inline_types.ts, src/test/inline_types_test.ts
The recent v0.10 tag changed positional type names into qualified names matching the source names.
This failed to consider inline types, which (while possibly valid) would be better served as positional names.
This PR addresses this issue as seen with this program:
```typescript
export function bar(x: {a: number, b: string}): string {
return 'hello';
}
```
corresponding to this change in schema:
```diff
"object_types": {
---        "{ a: number; b: string; }": {
+++        "bar_arguments_x": {
```
=> Use positional names for inline-types

src/infer.ts
Outputs listing on STDERR so that it can be ignored.
Example:
```
> deno run -A  /Users/lyndon/hasura/ndc-typescript-deno/src/mod.ts infer --vendor scratch/vendor scratch/funcs.ts
There were 1 diagnostic errors.
/Users/lyndon/hasura/ndc-typescript-deno/scratch/vendor/deno.land/x/sendgrid@0.0.3/mod.ts (123,5): Property '0' is missing in type 'string[]' but required in type 'RegExpMatchArray'.
Skipping non-exported function: bar
Procedures:
* send(subject, to, from, plain, html)
* transaction_count(address)
{"schema":{"scalar_types": ...
```
=> Outputting listing of functions and procedures when performing inference for convenience

Makefile, src/test/data/external_dependencies.ts, src/test/external_dependencies_test.ts
Deno doesn't currently support vendoring `npm:` sources, so this test will fail which is why it's currently ignored.
=> Adding (currently ignored) test to verify behaviour of external dependency usage

src/infer.ts, src/test/classes_test.ts, src/test/complex_dependency_test.ts, src/test/data/classes.ts, src/test/data/validation_algorithm_update.ts, src/test/data/void_types.ts, src/test/type_parameters_test.ts, src/test/validation_algorithm_test.ts, src/test/void_test.ts
Updating the validation algorithm to perform more robust validation of generic types.
Thanks to @daniel-chambers for the POC of the flag based object type function.
Fixes: https://github.com/hasura/ndc-typescript-deno/issues/61 - Use a better check for inline object type detection
Fixes: https://github.com/hasura/ndc-typescript-deno/issues/33 - Detect Object and Array scenarios using TS library functions
Fixes: https://github.com/hasura/ndc-typescript-deno/issues/45 - (Already Closed) - Infinite loop for certain function definitions
Fixes: https://github.com/hasura/ndc-typescript-deno/issues/51 - [Inferring result for non-annotated functions.](https://github.com/hasura/ndc-typescript-deno/issues/51)
Fixes: https://github.com/hasura/ndc-typescript-deno/issues/31 - Find a better …
=> Refinement of validation algorithm

CHANGELOG.md, src/infer.ts, src/test/data/pg_dep.ts, src/test/pg_dep_test.ts
Bug reported against v0.14.1
Fixed by updating TS target and libraries to 2022.
New test: `src/test/data/pg_dep.ts`
Example Reproduction - index.ts:
```typescript
import { Client } from "https://deno.land/x/postgres@v0.17.0/mod.ts";
const dbConfig = {
user: "asdfasdfasdfasdf",
hostname: "asdfasdfasdfasdf.us-west-2.aws.neon.tech",
port: 5432,
password: "asdfasdfasdfasdf",
database: "asdfasdfasdfasdf",
ssl: true,
sslmode: "require",
};
export async function insert_user(
user_name: string,
): Promise<
{ id: string; name: string; created_at: string } | { message: string } | {
error: string;
} | {}
> {
const client = new Client(dbConfig);
try {
await client.connect();
const result = await client.queryObject({
text: `INSERT INTO users(name) VALUES ('${user_name}') RETURNING *`,
});
if (result …
```
=> Updating TS target to 2022 to fix pg dependency bug

CHANGELOG.md, src/connector.ts, src/entrypoint.sh
In order to allow users to specify an empty object config, we should prevendor by default so dependencies 'just work'.
Fixes: https://github.com/hasura/ndc-typescript-deno/issues/71
=> `preVendor: true` by default

.gitignore, README.md, src/entrypoint.sh, src/infer.ts, src/test/external_dependencies_test.ts
This PR fixes #63 by doing a `deno vendor --node-modules-dir` to get Deno to create a node_modules directory for any npm modules used in the script. Then, we hook the compiler's module resolution process in `infer.ts` via the `resolveModuleNameLiterals` compiler host function, and when we see an `npm:pkgName[@version][/path]` module import, we extract the package name and get TypeScript to resolve that instead. It automatically looks in `node_modules` directories and finds the directory that `deno vendor --node-modules-dir` has symlinked in there from its NPM package cache.
Fixes: https://github.com/hasura/ndc-typescript-deno/issues/63
=> Fixed inference when using npm packages

CHANGELOG.md, src/connector.ts
Previous implementation of vendor defaults was incorrect: https://github.com/hasura/ndc-typescript-deno/pull/74
This PR addresses the issue by not requiring defaulting to occur in the configuration step.
=> Fixing implementation error for configuration defaults: `preVendor`

src/infer.ts
This PR ignores TypeScript diagnostic error codes that Deno itself ignores. It also fixes the target compilation language which got broken in #63's merge. Fatal errors occurring on a particular file are prefixed with FATAL too.
=> Fixed ES version and ignored TS compiler diagnostics that Deno ignores

.dockerignore, .github/workflows/deno.yml, CHANGELOG.md, Dockerfile, README.md, functions/index.ts, src/README.md, src/connector.ts, src/entrypoint.sh, src/infer.ts, src/mod.ts, src/test/classes_test.ts, src/test/complex_dependency_test.ts, src/test/conflicting_names_test.ts, src/test/external_dependencies_test.ts, src/test/infer_test.ts, src/test/inline_types_test.ts, src/test/pg_dep_test.ts, src/test/recursive_types_test.ts, src/test/type_parameters_test.ts, src/test/validation_algorithm_test.ts, src/test/void_test.ts
This PR improves support for running the connector using `deno run --watch` where the connector gets restarted by Deno whenever the function files change. It adds support for running the connector in watch mode using Docker.
```bash
docker build . -t "typescript-deno:latest" # only because we don't publish a docker container anywhere
docker run -it --rm -p 8080:8080 -e WATCH=1 -v ./functions:/functions/src typescript-deno:latest
```
Part of the improvements to make watch mode work better include
* rearranging when we infer the functions schema to reduce work done, but also reduce watch-induced reloads caused by vendoring during inference
* rearranging the dockerfile and entrypoint script so that the generated vendor, node_modules and schema.json artifacts are stored outside of the …
=> Improved `deno run --watch` support, watch support inside Docker

CHANGELOG.md, README.md
Updated readme with details about watching using the Docker container and the changelog for v0.20 release.
=> Updated readme and changelog for v0.20 release

.editorconfig, CHANGELOG.md, src/connector.ts, src/infer.ts, src/mod.ts, src/schema.ts, src/test/classes_test.ts, src/test/complex_dependency_test.ts, src/test/conflicting_names_test.ts, src/test/data/nullable_types.ts, src/test/external_dependencies_test.ts, src/test/infer_test.ts, src/test/inline_types_test.ts, src/test/ndc_schema_test.ts, src/test/nullable_types_test.ts, src/test/pg_dep_test.ts, src/test/prepare_arguments_test.ts, src/test/recursive_types_test.ts, src/test/type_parameters_test.ts, src/test/validation_algorithm_test.ts, src/test/void_test.ts, src/util.ts
This PR adds support for using "nullable" TypeScript types such as `String | null`, `String | undefined`, `String | null | undefined`, and optional object properties. These are expressed as nullable NDC types in the schema.
When null or omitted arguments/object properties are received in query, any null/omissions are coerced into what the type actually accepts. So:
* `string | null` -> coerce omissions to null, and explicit nulls are passed through.
* `string | undefined`  -> omission is passed as undefined, and explicit nulls are coerced to undefined.
* `string | null | undefined` you don't perform any coercions, omission is passed as undefined and explicit null is passed through
Some large refactoring has taken place to support this nicely. The inference process now produces a …
=> Support for Nullable Types

CHANGELOG.md, src/connector.ts
Partially addresses: https://github.com/hasura/ndc-typescript-deno/issues/24
Does not implement batching.
Returns multiple results in the format:
```javascript
[
{ '__value': result1 },
{ '__value': result2 }
]
```
Single variable set:
Multiple variable sets:
Missing variable:
Normal request:
=> Support Variables for default N+1 relationship queries

CHANGELOG.md, src/connector.ts, src/mod.ts, src/schema.ts, src/sdk.ts
SERVICE_TOKEN_SECRET wasn't being checked correctly in the SDK.
See PR: https://github.com/hasura/ndc-sdk-typescript/pull/11
- See CHANGELOG.md
> ## v0.22
>
> Update TS SDK Dependency to v1.2.6.
> 
> * Fixes issue with SERVICE_TOKEN check
=> Update ndc-sdk-typescript to v1.2.6 to address SERVICE_TOKEN issue

CHANGELOG.md, src/connector.ts, src/sdk.ts
Fixed response format being incorrect (multiple rows instead of multiple row sets!) when variables were used in the query request.
_(Select only one. In case of multiple, choose the most appropriate)_
Fixed queries with variables returning incorrect result format
=> Fixed queries with variables returning incorrect result format

CHANGELOG.md, README.md
Updated changelog with v0.23 version. Also fixed links to the Hasura 3 CLI installation docs in the readme.
=> Prepare v0.23 release

CHANGELOG.md, src/sdk.ts
This PR pins the version of Fastify used to ensure that we avoid using the latest version which is not compatible with Deno because it uses AsyncResource.emitDestroy.
Fastify incompatible changes:
- Add a changelog entry (in the "Changelog entry" section below) if the changes in this PR have any user-facing impact.
- If no changelog is required ignore/remove this section and add a `no-changelog-required` label to the PR.
_(Select only one. In case of multiple, choose the most appropriate)_
Pinned the Fastify version used to avoid using the latest version which does not work with Deno
=> Pin Fastify dependency version
